<?php
/**
 * Database Configuration Template
 *
 * This file will be generated by the installation wizard
 * Copy this file to database.php and customize the values for manual setup
 */

// Database connection settings
define('DB_HOST', 'localhost');     // Use 'db' for Docker environment
define('DB_PORT', '3306');
define('DB_NAME', 'family_tasks');
define('DB_USER', 'root');
define('DB_PASS', '');
